language: python
python:
  - "stable"

before_install:
  - pip install --user codecov
  - pip install coverage
script:
  - coverage run -m unittest discover
after_success:
  - codecov --file coverage/lcov.info --disable search
  - bash <(curl -s https://codecov.io/bash)
